export const GAME_DATA = {
  "startingCoins": [
    {
      "id": "starter_1",
      "name": "Starter Coin 1",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_2",
      "name": "Starter Coin 2",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_3",
      "name": "Starter Coin 3",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_4",
      "name": "Starter Coin 4",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_5",
      "name": "Starter Coin 5",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_6",
      "name": "Starter Coin 6",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_7",
      "name": "Starter Coin 7",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    },
    {
      "id": "starter_8",
      "name": "Starter Coin 8",
      "rarity": "starter",
      "value": 1,
      "cost": 0,
      "effectType": "NONE",
      "effectValue": 0,
      "text": "Kopf = 0, Zahl = 1.",
      "flavor": "Eine einfache Münze."
    }
  ],
  "coins": [
    {
      "id": "coin_001",
      "name": "Bronze Coin 1",
      "rarity": "common",
      "value": 1,
      "cost": 3,
      "effectType": "tailsBonus",
      "effectValue": 1,
      "text": "Zahl gibt +1 extra Punkte.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_002",
      "name": "Bronze Coin 2",
      "rarity": "common",
      "value": 1,
      "cost": 4,
      "effectType": "headsValue",
      "effectValue": 1,
      "text": "Kopf gibt 1 Punkte statt 0.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_003",
      "name": "Bronze Coin 3",
      "rarity": "common",
      "value": 1,
      "cost": 5,
      "effectType": "tailBias",
      "effectValue": 15,
      "text": "+15% Chance auf Zahl.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_004",
      "name": "Bronze Coin 4",
      "rarity": "common",
      "value": 1,
      "cost": 6,
      "effectType": "rerollHeadsChance",
      "effectValue": 9,
      "text": "Wenn Kopf fällt: 9% Chance auf automatischen Nachwurf.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_005",
      "name": "Bronze Coin 5",
      "rarity": "common",
      "value": 2,
      "cost": 7,
      "effectType": "tailMultiplier",
      "effectValue": 1.45,
      "text": "Bei Zahl: x1.45 Multiplikator auf den Münzwert.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_006",
      "name": "Bronze Coin 6",
      "rarity": "common",
      "value": 2,
      "cost": 8,
      "effectType": "flatPerThrow",
      "effectValue": 2,
      "text": "Am Ende jedes Wurfs +2 Punkte.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_007",
      "name": "Bronze Coin 7",
      "rarity": "common",
      "value": 2,
      "cost": 9,
      "effectType": "comboTails",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +2 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_008",
      "name": "Bronze Coin 8",
      "rarity": "common",
      "value": 2,
      "cost": 10,
      "effectType": "comboHeads",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +2 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_009",
      "name": "Bronze Coin 9",
      "rarity": "common",
      "value": 3,
      "cost": 11,
      "effectType": "tripleTailBonus",
      "effectValue": 2,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +2 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_010",
      "name": "Bronze Coin 10",
      "rarity": "common",
      "value": 3,
      "cost": 12,
      "effectType": "nextBias",
      "effectValue": 13,
      "text": "Nach einem Kopf: nächste Runde +13% Zahl-Chance.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_011",
      "name": "Bronze Coin 11",
      "rarity": "common",
      "value": 3,
      "cost": 13,
      "effectType": "neighborTailBonus",
      "effectValue": 3,
      "text": "Nachbarn erhalten bei Zahl +3.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_012",
      "name": "Bronze Coin 12",
      "rarity": "common",
      "value": 3,
      "cost": 14,
      "effectType": "interest",
      "effectValue": 23,
      "text": "Nach Rundenende +23% Zinsen auf überschüssige Punkte.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_013",
      "name": "Bronze Coin 13",
      "rarity": "common",
      "value": 4,
      "cost": 15,
      "effectType": "charmBias",
      "effectValue": 17,
      "text": "Jeder Glücksbringer gibt dieser Münze +17% Zahl-Chance.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_014",
      "name": "Bronze Coin 14",
      "rarity": "common",
      "value": 4,
      "cost": 16,
      "effectType": "echoPercent",
      "effectValue": 20,
      "text": "Wiederholt 20% ihres letzten Zahl-Werts.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_015",
      "name": "Bronze Coin 15",
      "rarity": "common",
      "value": 4,
      "cost": 17,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.25,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.25 auf diese Münze.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_016",
      "name": "Silver Coin 1",
      "rarity": "common",
      "value": 2,
      "cost": 6,
      "effectType": "headsValue",
      "effectValue": 1,
      "text": "Kopf gibt 1 Punkte statt 0.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_017",
      "name": "Silver Coin 2",
      "rarity": "common",
      "value": 2,
      "cost": 7,
      "effectType": "tailBias",
      "effectValue": 12,
      "text": "+12% Chance auf Zahl.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_018",
      "name": "Silver Coin 3",
      "rarity": "common",
      "value": 2,
      "cost": 8,
      "effectType": "rerollHeadsChance",
      "effectValue": 15,
      "text": "Wenn Kopf fällt: 15% Chance auf automatischen Nachwurf.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_019",
      "name": "Silver Coin 4",
      "rarity": "common",
      "value": 2,
      "cost": 9,
      "effectType": "tailMultiplier",
      "effectValue": 1.9,
      "text": "Bei Zahl: x1.9 Multiplikator auf den Münzwert.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_020",
      "name": "Silver Coin 5",
      "rarity": "common",
      "value": 3,
      "cost": 10,
      "effectType": "flatPerThrow",
      "effectValue": 1,
      "text": "Am Ende jedes Wurfs +1 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_021",
      "name": "Silver Coin 6",
      "rarity": "common",
      "value": 3,
      "cost": 11,
      "effectType": "comboTails",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +2 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_022",
      "name": "Silver Coin 7",
      "rarity": "common",
      "value": 3,
      "cost": 12,
      "effectType": "comboHeads",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +2 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_023",
      "name": "Silver Coin 8",
      "rarity": "common",
      "value": 3,
      "cost": 13,
      "effectType": "tripleTailBonus",
      "effectValue": 2,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +2 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_024",
      "name": "Silver Coin 9",
      "rarity": "common",
      "value": 4,
      "cost": 14,
      "effectType": "nextBias",
      "effectValue": 19,
      "text": "Nach einem Kopf: nächste Runde +19% Zahl-Chance.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_025",
      "name": "Silver Coin 10",
      "rarity": "common",
      "value": 4,
      "cost": 15,
      "effectType": "neighborTailBonus",
      "effectValue": 2,
      "text": "Nachbarn erhalten bei Zahl +2.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_026",
      "name": "Silver Coin 11",
      "rarity": "common",
      "value": 4,
      "cost": 16,
      "effectType": "interest",
      "effectValue": 20,
      "text": "Nach Rundenende +20% Zinsen auf überschüssige Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_027",
      "name": "Silver Coin 12",
      "rarity": "common",
      "value": 4,
      "cost": 17,
      "effectType": "charmBias",
      "effectValue": 23,
      "text": "Jeder Glücksbringer gibt dieser Münze +23% Zahl-Chance.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_028",
      "name": "Silver Coin 13",
      "rarity": "common",
      "value": 5,
      "cost": 18,
      "effectType": "echoPercent",
      "effectValue": 17,
      "text": "Wiederholt 17% ihres letzten Zahl-Werts.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_029",
      "name": "Silver Coin 14",
      "rarity": "common",
      "value": 5,
      "cost": 19,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.1,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.1 auf diese Münze.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_030",
      "name": "Silver Coin 15",
      "rarity": "common",
      "value": 5,
      "cost": 20,
      "effectType": "tailsBonus",
      "effectValue": 3,
      "text": "Zahl gibt +3 extra Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_031",
      "name": "Gold Coin 1",
      "rarity": "uncommon",
      "value": 3,
      "cost": 9,
      "effectType": "tailBias",
      "effectValue": 13,
      "text": "+13% Chance auf Zahl.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_032",
      "name": "Gold Coin 2",
      "rarity": "uncommon",
      "value": 3,
      "cost": 10,
      "effectType": "rerollHeadsChance",
      "effectValue": 16,
      "text": "Wenn Kopf fällt: 16% Chance auf automatischen Nachwurf.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_033",
      "name": "Gold Coin 3",
      "rarity": "uncommon",
      "value": 3,
      "cost": 11,
      "effectType": "tailMultiplier",
      "effectValue": 2.0,
      "text": "Bei Zahl: x2.0 Multiplikator auf den Münzwert.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_034",
      "name": "Gold Coin 4",
      "rarity": "uncommon",
      "value": 3,
      "cost": 12,
      "effectType": "flatPerThrow",
      "effectValue": 2,
      "text": "Am Ende jedes Wurfs +2 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_035",
      "name": "Gold Coin 5",
      "rarity": "uncommon",
      "value": 4,
      "cost": 13,
      "effectType": "comboTails",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +2 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_036",
      "name": "Gold Coin 6",
      "rarity": "uncommon",
      "value": 4,
      "cost": 14,
      "effectType": "comboHeads",
      "effectValue": 3,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +3 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_037",
      "name": "Gold Coin 7",
      "rarity": "uncommon",
      "value": 4,
      "cost": 15,
      "effectType": "tripleTailBonus",
      "effectValue": 3,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +3 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_038",
      "name": "Gold Coin 8",
      "rarity": "uncommon",
      "value": 4,
      "cost": 16,
      "effectType": "nextBias",
      "effectValue": 20,
      "text": "Nach einem Kopf: nächste Runde +20% Zahl-Chance.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_039",
      "name": "Gold Coin 9",
      "rarity": "uncommon",
      "value": 5,
      "cost": 17,
      "effectType": "neighborTailBonus",
      "effectValue": 3,
      "text": "Nachbarn erhalten bei Zahl +3.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_040",
      "name": "Gold Coin 10",
      "rarity": "uncommon",
      "value": 5,
      "cost": 18,
      "effectType": "interest",
      "effectValue": 17,
      "text": "Nach Rundenende +17% Zinsen auf überschüssige Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_041",
      "name": "Gold Coin 11",
      "rarity": "uncommon",
      "value": 5,
      "cost": 19,
      "effectType": "charmBias",
      "effectValue": 24,
      "text": "Jeder Glücksbringer gibt dieser Münze +24% Zahl-Chance.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_042",
      "name": "Gold Coin 12",
      "rarity": "uncommon",
      "value": 5,
      "cost": 20,
      "effectType": "echoPercent",
      "effectValue": 27,
      "text": "Wiederholt 27% ihres letzten Zahl-Werts.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_043",
      "name": "Gold Coin 13",
      "rarity": "uncommon",
      "value": 6,
      "cost": 21,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.2,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.2 auf diese Münze.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_044",
      "name": "Gold Coin 14",
      "rarity": "uncommon",
      "value": 6,
      "cost": 22,
      "effectType": "tailsBonus",
      "effectValue": 4,
      "text": "Zahl gibt +4 extra Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_045",
      "name": "Gold Coin 15",
      "rarity": "uncommon",
      "value": 6,
      "cost": 23,
      "effectType": "headsValue",
      "effectValue": 4,
      "text": "Kopf gibt 4 Punkte statt 0.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_046",
      "name": "Obsidian Coin 1",
      "rarity": "uncommon",
      "value": 4,
      "cost": 12,
      "effectType": "rerollHeadsChance",
      "effectValue": 13,
      "text": "Wenn Kopf fällt: 13% Chance auf automatischen Nachwurf.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_047",
      "name": "Obsidian Coin 2",
      "rarity": "uncommon",
      "value": 4,
      "cost": 13,
      "effectType": "tailMultiplier",
      "effectValue": 1.85,
      "text": "Bei Zahl: x1.85 Multiplikator auf den Münzwert.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_048",
      "name": "Obsidian Coin 3",
      "rarity": "uncommon",
      "value": 4,
      "cost": 14,
      "effectType": "flatPerThrow",
      "effectValue": 2,
      "text": "Am Ende jedes Wurfs +2 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_049",
      "name": "Obsidian Coin 4",
      "rarity": "uncommon",
      "value": 4,
      "cost": 15,
      "effectType": "comboTails",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +2 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_050",
      "name": "Obsidian Coin 5",
      "rarity": "uncommon",
      "value": 5,
      "cost": 16,
      "effectType": "comboHeads",
      "effectValue": 2,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +2 Punkte.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_051",
      "name": "Obsidian Coin 6",
      "rarity": "uncommon",
      "value": 5,
      "cost": 17,
      "effectType": "tripleTailBonus",
      "effectValue": 3,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +3 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_052",
      "name": "Obsidian Coin 7",
      "rarity": "uncommon",
      "value": 5,
      "cost": 18,
      "effectType": "nextBias",
      "effectValue": 17,
      "text": "Nach einem Kopf: nächste Runde +17% Zahl-Chance.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_053",
      "name": "Obsidian Coin 8",
      "rarity": "uncommon",
      "value": 5,
      "cost": 19,
      "effectType": "neighborTailBonus",
      "effectValue": 3,
      "text": "Nachbarn erhalten bei Zahl +3.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_054",
      "name": "Obsidian Coin 9",
      "rarity": "uncommon",
      "value": 6,
      "cost": 20,
      "effectType": "interest",
      "effectValue": 23,
      "text": "Nach Rundenende +23% Zinsen auf überschüssige Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_055",
      "name": "Obsidian Coin 10",
      "rarity": "uncommon",
      "value": 6,
      "cost": 21,
      "effectType": "charmBias",
      "effectValue": 17,
      "text": "Jeder Glücksbringer gibt dieser Münze +17% Zahl-Chance.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_056",
      "name": "Obsidian Coin 11",
      "rarity": "uncommon",
      "value": 6,
      "cost": 22,
      "effectType": "echoPercent",
      "effectValue": 24,
      "text": "Wiederholt 24% ihres letzten Zahl-Werts.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_057",
      "name": "Obsidian Coin 12",
      "rarity": "uncommon",
      "value": 6,
      "cost": 23,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.65,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.65 auf diese Münze.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_058",
      "name": "Obsidian Coin 13",
      "rarity": "uncommon",
      "value": 7,
      "cost": 24,
      "effectType": "tailsBonus",
      "effectValue": 4,
      "text": "Zahl gibt +4 extra Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_059",
      "name": "Obsidian Coin 14",
      "rarity": "uncommon",
      "value": 7,
      "cost": 25,
      "effectType": "headsValue",
      "effectValue": 4,
      "text": "Kopf gibt 4 Punkte statt 0.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_060",
      "name": "Obsidian Coin 15",
      "rarity": "uncommon",
      "value": 7,
      "cost": 26,
      "effectType": "tailBias",
      "effectValue": 27,
      "text": "+27% Chance auf Zahl.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_061",
      "name": "Neon Coin 1",
      "rarity": "rare",
      "value": 5,
      "cost": 15,
      "effectType": "tailMultiplier",
      "effectValue": 1.95,
      "text": "Bei Zahl: x1.95 Multiplikator auf den Münzwert.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_062",
      "name": "Neon Coin 2",
      "rarity": "rare",
      "value": 5,
      "cost": 16,
      "effectType": "flatPerThrow",
      "effectValue": 3,
      "text": "Am Ende jedes Wurfs +3 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_063",
      "name": "Neon Coin 3",
      "rarity": "rare",
      "value": 5,
      "cost": 17,
      "effectType": "comboTails",
      "effectValue": 3,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +3 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_064",
      "name": "Neon Coin 4",
      "rarity": "rare",
      "value": 5,
      "cost": 18,
      "effectType": "comboHeads",
      "effectValue": 3,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +3 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_065",
      "name": "Neon Coin 5",
      "rarity": "rare",
      "value": 6,
      "cost": 19,
      "effectType": "tripleTailBonus",
      "effectValue": 3,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +3 Punkte.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_066",
      "name": "Neon Coin 6",
      "rarity": "rare",
      "value": 6,
      "cost": 20,
      "effectType": "nextBias",
      "effectValue": 27,
      "text": "Nach einem Kopf: nächste Runde +27% Zahl-Chance.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_067",
      "name": "Neon Coin 7",
      "rarity": "rare",
      "value": 6,
      "cost": 21,
      "effectType": "neighborTailBonus",
      "effectValue": 4,
      "text": "Nachbarn erhalten bei Zahl +4.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_068",
      "name": "Neon Coin 8",
      "rarity": "rare",
      "value": 6,
      "cost": 22,
      "effectType": "interest",
      "effectValue": 24,
      "text": "Nach Rundenende +24% Zinsen auf überschüssige Punkte.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_069",
      "name": "Neon Coin 9",
      "rarity": "rare",
      "value": 7,
      "cost": 23,
      "effectType": "charmBias",
      "effectValue": 27,
      "text": "Jeder Glücksbringer gibt dieser Münze +27% Zahl-Chance.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_070",
      "name": "Neon Coin 10",
      "rarity": "rare",
      "value": 7,
      "cost": 24,
      "effectType": "echoPercent",
      "effectValue": 21,
      "text": "Wiederholt 21% ihres letzten Zahl-Werts.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_071",
      "name": "Neon Coin 11",
      "rarity": "rare",
      "value": 7,
      "cost": 25,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.75,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.75 auf diese Münze.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_072",
      "name": "Neon Coin 12",
      "rarity": "rare",
      "value": 7,
      "cost": 26,
      "effectType": "tailsBonus",
      "effectValue": 5,
      "text": "Zahl gibt +5 extra Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_073",
      "name": "Neon Coin 13",
      "rarity": "rare",
      "value": 8,
      "cost": 27,
      "effectType": "headsValue",
      "effectValue": 5,
      "text": "Kopf gibt 5 Punkte statt 0.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_074",
      "name": "Neon Coin 14",
      "rarity": "rare",
      "value": 8,
      "cost": 28,
      "effectType": "tailBias",
      "effectValue": 28,
      "text": "+28% Chance auf Zahl.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_075",
      "name": "Neon Coin 15",
      "rarity": "rare",
      "value": 8,
      "cost": 29,
      "effectType": "rerollHeadsChance",
      "effectValue": 31,
      "text": "Wenn Kopf fällt: 31% Chance auf automatischen Nachwurf.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_076",
      "name": "Void Coin 1",
      "rarity": "rare",
      "value": 6,
      "cost": 18,
      "effectType": "flatPerThrow",
      "effectValue": 3,
      "text": "Am Ende jedes Wurfs +3 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_077",
      "name": "Void Coin 2",
      "rarity": "rare",
      "value": 6,
      "cost": 19,
      "effectType": "comboTails",
      "effectValue": 3,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +3 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_078",
      "name": "Void Coin 3",
      "rarity": "rare",
      "value": 6,
      "cost": 20,
      "effectType": "comboHeads",
      "effectValue": 3,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +3 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_079",
      "name": "Void Coin 4",
      "rarity": "rare",
      "value": 6,
      "cost": 21,
      "effectType": "tripleTailBonus",
      "effectValue": 3,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +3 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_080",
      "name": "Void Coin 5",
      "rarity": "rare",
      "value": 7,
      "cost": 22,
      "effectType": "nextBias",
      "effectValue": 20,
      "text": "Nach einem Kopf: nächste Runde +20% Zahl-Chance.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_081",
      "name": "Void Coin 6",
      "rarity": "rare",
      "value": 7,
      "cost": 23,
      "effectType": "neighborTailBonus",
      "effectValue": 4,
      "text": "Nachbarn erhalten bei Zahl +4.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_082",
      "name": "Void Coin 7",
      "rarity": "rare",
      "value": 7,
      "cost": 24,
      "effectType": "interest",
      "effectValue": 21,
      "text": "Nach Rundenende +21% Zinsen auf überschüssige Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_083",
      "name": "Void Coin 8",
      "rarity": "rare",
      "value": 7,
      "cost": 25,
      "effectType": "charmBias",
      "effectValue": 24,
      "text": "Jeder Glücksbringer gibt dieser Münze +24% Zahl-Chance.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_084",
      "name": "Void Coin 9",
      "rarity": "rare",
      "value": 8,
      "cost": 26,
      "effectType": "echoPercent",
      "effectValue": 27,
      "text": "Wiederholt 27% ihres letzten Zahl-Werts.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_085",
      "name": "Void Coin 10",
      "rarity": "rare",
      "value": 8,
      "cost": 27,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.35,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.35 auf diese Münze.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_086",
      "name": "Void Coin 11",
      "rarity": "rare",
      "value": 8,
      "cost": 28,
      "effectType": "tailsBonus",
      "effectValue": 5,
      "text": "Zahl gibt +5 extra Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_087",
      "name": "Void Coin 12",
      "rarity": "rare",
      "value": 8,
      "cost": 29,
      "effectType": "headsValue",
      "effectValue": 5,
      "text": "Kopf gibt 5 Punkte statt 0.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_088",
      "name": "Void Coin 13",
      "rarity": "rare",
      "value": 9,
      "cost": 30,
      "effectType": "tailBias",
      "effectValue": 25,
      "text": "+25% Chance auf Zahl.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_089",
      "name": "Void Coin 14",
      "rarity": "rare",
      "value": 9,
      "cost": 31,
      "effectType": "rerollHeadsChance",
      "effectValue": 28,
      "text": "Wenn Kopf fällt: 28% Chance auf automatischen Nachwurf.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_090",
      "name": "Void Coin 15",
      "rarity": "rare",
      "value": 9,
      "cost": 32,
      "effectType": "tailMultiplier",
      "effectValue": 2.75,
      "text": "Bei Zahl: x2.75 Multiplikator auf den Münzwert.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_091",
      "name": "Saint Coin 1",
      "rarity": "epic",
      "value": 7,
      "cost": 21,
      "effectType": "comboTails",
      "effectValue": 4,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +4 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_092",
      "name": "Saint Coin 2",
      "rarity": "epic",
      "value": 7,
      "cost": 22,
      "effectType": "comboHeads",
      "effectValue": 4,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +4 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_093",
      "name": "Saint Coin 3",
      "rarity": "epic",
      "value": 7,
      "cost": 23,
      "effectType": "tripleTailBonus",
      "effectValue": 4,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +4 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_094",
      "name": "Saint Coin 4",
      "rarity": "epic",
      "value": 7,
      "cost": 24,
      "effectType": "nextBias",
      "effectValue": 21,
      "text": "Nach einem Kopf: nächste Runde +21% Zahl-Chance.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_095",
      "name": "Saint Coin 5",
      "rarity": "epic",
      "value": 8,
      "cost": 25,
      "effectType": "neighborTailBonus",
      "effectValue": 4,
      "text": "Nachbarn erhalten bei Zahl +4.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_096",
      "name": "Saint Coin 6",
      "rarity": "epic",
      "value": 8,
      "cost": 26,
      "effectType": "interest",
      "effectValue": 31,
      "text": "Nach Rundenende +31% Zinsen auf überschüssige Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_097",
      "name": "Saint Coin 7",
      "rarity": "epic",
      "value": 8,
      "cost": 27,
      "effectType": "charmBias",
      "effectValue": 25,
      "text": "Jeder Glücksbringer gibt dieser Münze +25% Zahl-Chance.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_098",
      "name": "Saint Coin 8",
      "rarity": "epic",
      "value": 8,
      "cost": 28,
      "effectType": "echoPercent",
      "effectValue": 28,
      "text": "Wiederholt 28% ihres letzten Zahl-Werts.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_099",
      "name": "Saint Coin 9",
      "rarity": "epic",
      "value": 9,
      "cost": 29,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.45,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.45 auf diese Münze.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_100",
      "name": "Saint Coin 10",
      "rarity": "epic",
      "value": 9,
      "cost": 30,
      "effectType": "tailsBonus",
      "effectValue": 5,
      "text": "Zahl gibt +5 extra Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_101",
      "name": "Saint Coin 11",
      "rarity": "epic",
      "value": 9,
      "cost": 31,
      "effectType": "headsValue",
      "effectValue": 6,
      "text": "Kopf gibt 6 Punkte statt 0.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_102",
      "name": "Saint Coin 12",
      "rarity": "epic",
      "value": 9,
      "cost": 32,
      "effectType": "tailBias",
      "effectValue": 35,
      "text": "+35% Chance auf Zahl.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_103",
      "name": "Saint Coin 13",
      "rarity": "epic",
      "value": 10,
      "cost": 33,
      "effectType": "rerollHeadsChance",
      "effectValue": 29,
      "text": "Wenn Kopf fällt: 29% Chance auf automatischen Nachwurf.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_104",
      "name": "Saint Coin 14",
      "rarity": "epic",
      "value": 10,
      "cost": 34,
      "effectType": "tailMultiplier",
      "effectValue": 2.85,
      "text": "Bei Zahl: x2.85 Multiplikator auf den Münzwert.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_105",
      "name": "Saint Coin 15",
      "rarity": "epic",
      "value": 10,
      "cost": 35,
      "effectType": "flatPerThrow",
      "effectValue": 6,
      "text": "Am Ende jedes Wurfs +6 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_106",
      "name": "Glitch Coin 1",
      "rarity": "epic",
      "value": 8,
      "cost": 24,
      "effectType": "comboHeads",
      "effectValue": 4,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +4 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_107",
      "name": "Glitch Coin 2",
      "rarity": "epic",
      "value": 8,
      "cost": 25,
      "effectType": "tripleTailBonus",
      "effectValue": 4,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +4 Punkte.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_108",
      "name": "Glitch Coin 3",
      "rarity": "epic",
      "value": 8,
      "cost": 26,
      "effectType": "nextBias",
      "effectValue": 27,
      "text": "Nach einem Kopf: nächste Runde +27% Zahl-Chance.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_109",
      "name": "Glitch Coin 4",
      "rarity": "epic",
      "value": 8,
      "cost": 27,
      "effectType": "neighborTailBonus",
      "effectValue": 4,
      "text": "Nachbarn erhalten bei Zahl +4.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_110",
      "name": "Glitch Coin 5",
      "rarity": "epic",
      "value": 9,
      "cost": 28,
      "effectType": "interest",
      "effectValue": 24,
      "text": "Nach Rundenende +24% Zinsen auf überschüssige Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_111",
      "name": "Glitch Coin 6",
      "rarity": "epic",
      "value": 9,
      "cost": 29,
      "effectType": "charmBias",
      "effectValue": 31,
      "text": "Jeder Glücksbringer gibt dieser Münze +31% Zahl-Chance.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_112",
      "name": "Glitch Coin 7",
      "rarity": "epic",
      "value": 9,
      "cost": 30,
      "effectType": "echoPercent",
      "effectValue": 25,
      "text": "Wiederholt 25% ihres letzten Zahl-Werts.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_113",
      "name": "Glitch Coin 8",
      "rarity": "epic",
      "value": 9,
      "cost": 31,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.9,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.9 auf diese Münze.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_114",
      "name": "Glitch Coin 9",
      "rarity": "epic",
      "value": 10,
      "cost": 32,
      "effectType": "tailsBonus",
      "effectValue": 5,
      "text": "Zahl gibt +5 extra Punkte.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_115",
      "name": "Glitch Coin 10",
      "rarity": "epic",
      "value": 10,
      "cost": 33,
      "effectType": "headsValue",
      "effectValue": 5,
      "text": "Kopf gibt 5 Punkte statt 0.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_116",
      "name": "Glitch Coin 11",
      "rarity": "epic",
      "value": 10,
      "cost": 34,
      "effectType": "tailBias",
      "effectValue": 32,
      "text": "+32% Chance auf Zahl.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_117",
      "name": "Glitch Coin 12",
      "rarity": "epic",
      "value": 10,
      "cost": 35,
      "effectType": "rerollHeadsChance",
      "effectValue": 35,
      "text": "Wenn Kopf fällt: 35% Chance auf automatischen Nachwurf.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_118",
      "name": "Glitch Coin 13",
      "rarity": "epic",
      "value": 11,
      "cost": 36,
      "effectType": "tailMultiplier",
      "effectValue": 2.7,
      "text": "Bei Zahl: x2.7 Multiplikator auf den Münzwert.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_119",
      "name": "Glitch Coin 14",
      "rarity": "epic",
      "value": 11,
      "cost": 37,
      "effectType": "flatPerThrow",
      "effectValue": 6,
      "text": "Am Ende jedes Wurfs +6 Punkte.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_120",
      "name": "Glitch Coin 15",
      "rarity": "epic",
      "value": 11,
      "cost": 38,
      "effectType": "comboTails",
      "effectValue": 6,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +6 Punkte.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_121",
      "name": "Royal Coin 1",
      "rarity": "legendary",
      "value": 10,
      "cost": 27,
      "effectType": "tripleTailBonus",
      "effectValue": 5,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +5 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_122",
      "name": "Royal Coin 2",
      "rarity": "legendary",
      "value": 10,
      "cost": 28,
      "effectType": "nextBias",
      "effectValue": 28,
      "text": "Nach einem Kopf: nächste Runde +28% Zahl-Chance.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_123",
      "name": "Royal Coin 3",
      "rarity": "legendary",
      "value": 10,
      "cost": 29,
      "effectType": "neighborTailBonus",
      "effectValue": 5,
      "text": "Nachbarn erhalten bei Zahl +5.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_124",
      "name": "Royal Coin 4",
      "rarity": "legendary",
      "value": 10,
      "cost": 30,
      "effectType": "interest",
      "effectValue": 25,
      "text": "Nach Rundenende +25% Zinsen auf überschüssige Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_125",
      "name": "Royal Coin 5",
      "rarity": "legendary",
      "value": 11,
      "cost": 31,
      "effectType": "charmBias",
      "effectValue": 28,
      "text": "Jeder Glücksbringer gibt dieser Münze +28% Zahl-Chance.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_126",
      "name": "Royal Coin 6",
      "rarity": "legendary",
      "value": 11,
      "cost": 32,
      "effectType": "echoPercent",
      "effectValue": 35,
      "text": "Wiederholt 35% ihres letzten Zahl-Werts.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_127",
      "name": "Royal Coin 7",
      "rarity": "legendary",
      "value": 11,
      "cost": 33,
      "effectType": "jackpotMultiplier",
      "effectValue": 3.0,
      "text": "Wenn alle 3 Würfe Zahl sind: x3.0 auf diese Münze.",
      "flavor": "Hat eine winzige Kerbe am Rand."
    },
    {
      "id": "coin_128",
      "name": "Royal Coin 8",
      "rarity": "legendary",
      "value": 11,
      "cost": 34,
      "effectType": "tailsBonus",
      "effectValue": 6,
      "text": "Zahl gibt +6 extra Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_129",
      "name": "Royal Coin 9",
      "rarity": "legendary",
      "value": 12,
      "cost": 35,
      "effectType": "headsValue",
      "effectValue": 6,
      "text": "Kopf gibt 6 Punkte statt 0.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_130",
      "name": "Royal Coin 10",
      "rarity": "legendary",
      "value": 12,
      "cost": 36,
      "effectType": "tailBias",
      "effectValue": 29,
      "text": "+29% Chance auf Zahl.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_131",
      "name": "Royal Coin 11",
      "rarity": "legendary",
      "value": 12,
      "cost": 37,
      "effectType": "rerollHeadsChance",
      "effectValue": 36,
      "text": "Wenn Kopf fällt: 36% Chance auf automatischen Nachwurf.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_132",
      "name": "Royal Coin 12",
      "rarity": "legendary",
      "value": 12,
      "cost": 38,
      "effectType": "tailMultiplier",
      "effectValue": 3.4,
      "text": "Bei Zahl: x3.4 Multiplikator auf den Münzwert.",
      "flavor": "Sieht wertlos aus, bis sie fällt."
    },
    {
      "id": "coin_133",
      "name": "Royal Coin 13",
      "rarity": "legendary",
      "value": 13,
      "cost": 39,
      "effectType": "flatPerThrow",
      "effectValue": 7,
      "text": "Am Ende jedes Wurfs +7 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_134",
      "name": "Royal Coin 14",
      "rarity": "legendary",
      "value": 13,
      "cost": 40,
      "effectType": "comboTails",
      "effectValue": 7,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +7 Punkte.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_135",
      "name": "Royal Coin 15",
      "rarity": "legendary",
      "value": 13,
      "cost": 41,
      "effectType": "comboHeads",
      "effectValue": 7,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +7 Punkte.",
      "flavor": "Flackert im blauen Licht."
    },
    {
      "id": "coin_136",
      "name": "Quantum Coin 1",
      "rarity": "legendary",
      "value": 12,
      "cost": 30,
      "effectType": "nextBias",
      "effectValue": 25,
      "text": "Nach einem Kopf: nächste Runde +25% Zahl-Chance.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_137",
      "name": "Quantum Coin 2",
      "rarity": "legendary",
      "value": 12,
      "cost": 31,
      "effectType": "neighborTailBonus",
      "effectValue": 5,
      "text": "Nachbarn erhalten bei Zahl +5.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_138",
      "name": "Quantum Coin 3",
      "rarity": "legendary",
      "value": 12,
      "cost": 32,
      "effectType": "interest",
      "effectValue": 31,
      "text": "Nach Rundenende +31% Zinsen auf überschüssige Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_139",
      "name": "Quantum Coin 4",
      "rarity": "legendary",
      "value": 12,
      "cost": 33,
      "effectType": "charmBias",
      "effectValue": 25,
      "text": "Jeder Glücksbringer gibt dieser Münze +25% Zahl-Chance.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_140",
      "name": "Quantum Coin 5",
      "rarity": "legendary",
      "value": 13,
      "cost": 34,
      "effectType": "echoPercent",
      "effectValue": 28,
      "text": "Wiederholt 28% ihres letzten Zahl-Werts.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_141",
      "name": "Quantum Coin 6",
      "rarity": "legendary",
      "value": 13,
      "cost": 35,
      "effectType": "jackpotMultiplier",
      "effectValue": 2.85,
      "text": "Wenn alle 3 Würfe Zahl sind: x2.85 auf diese Münze.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_142",
      "name": "Quantum Coin 7",
      "rarity": "legendary",
      "value": 13,
      "cost": 36,
      "effectType": "tailsBonus",
      "effectValue": 6,
      "text": "Zahl gibt +6 extra Punkte.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_143",
      "name": "Quantum Coin 8",
      "rarity": "legendary",
      "value": 13,
      "cost": 37,
      "effectType": "headsValue",
      "effectValue": 6,
      "text": "Kopf gibt 6 Punkte statt 0.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_144",
      "name": "Quantum Coin 9",
      "rarity": "legendary",
      "value": 14,
      "cost": 38,
      "effectType": "tailBias",
      "effectValue": 35,
      "text": "+35% Chance auf Zahl.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_145",
      "name": "Quantum Coin 10",
      "rarity": "legendary",
      "value": 14,
      "cost": 39,
      "effectType": "rerollHeadsChance",
      "effectValue": 29,
      "text": "Wenn Kopf fällt: 29% Chance auf automatischen Nachwurf.",
      "flavor": "Klingt nach Regen in einer Spielhalle."
    },
    {
      "id": "coin_146",
      "name": "Quantum Coin 11",
      "rarity": "legendary",
      "value": 14,
      "cost": 40,
      "effectType": "tailMultiplier",
      "effectValue": 3.25,
      "text": "Bei Zahl: x3.25 Multiplikator auf den Münzwert.",
      "flavor": "Kalt wie Automatenglas."
    },
    {
      "id": "coin_147",
      "name": "Quantum Coin 12",
      "rarity": "legendary",
      "value": 14,
      "cost": 41,
      "effectType": "flatPerThrow",
      "effectValue": 7,
      "text": "Am Ende jedes Wurfs +7 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_148",
      "name": "Quantum Coin 13",
      "rarity": "legendary",
      "value": 15,
      "cost": 42,
      "effectType": "comboTails",
      "effectValue": 7,
      "text": "Wenn mindestens 5 Zahlen im Wurf sind: +7 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_149",
      "name": "Quantum Coin 14",
      "rarity": "legendary",
      "value": 15,
      "cost": 43,
      "effectType": "comboHeads",
      "effectValue": 7,
      "text": "Wenn mindestens 5 Köpfe im Wurf sind: +7 Punkte.",
      "flavor": "Summt leise in der Tasche."
    },
    {
      "id": "coin_150",
      "name": "Quantum Coin 15",
      "rarity": "legendary",
      "value": 15,
      "cost": 44,
      "effectType": "tripleTailBonus",
      "effectValue": 7,
      "text": "Wenn diese Münze dreimal Zahl zeigt: +7 Punkte.",
      "flavor": "Flackert im blauen Licht."
    }
  ],
  "charms": [
    {
      "id": "charm_clover",
      "name": "Vierblatt-Klee",
      "cost": 6,
      "text": "+5% Zahl-Chance für alle Münzen.",
      "type": "globalTailBias",
      "value": 5
    },
    {
      "id": "charm_blue_lamp",
      "name": "Blaue Lampe",
      "cost": 7,
      "text": "Köpfe geben +1 Punkt.",
      "type": "globalHeadsValue",
      "value": 1
    },
    {
      "id": "charm_magnet",
      "name": "Taschenmagnet",
      "cost": 8,
      "text": "+1 auf alle Zahl-Ergebnisse.",
      "type": "globalTailBonus",
      "value": 1
    },
    {
      "id": "charm_echo",
      "name": "Echo-Fassung",
      "cost": 10,
      "text": "10% des letzten Wurfwerts wird wiederholt.",
      "type": "echoLastThrow",
      "value": 10
    },
    {
      "id": "charm_cashbox",
      "name": "Kasse ohne Boden",
      "cost": 10,
      "text": "+10% Bonus auf Rundenüberschuss.",
      "type": "surplusBonus",
      "value": 10
    },
    {
      "id": "charm_gear",
      "name": "Messingzahnrad",
      "cost": 12,
      "text": "Jeder dritte Wurf erhält x1.25.",
      "type": "thirdThrowMult",
      "value": 1.25
    },
    {
      "id": "charm_static",
      "name": "Statische Nadel",
      "cost": 11,
      "text": "Bei 6+ Zahlen im Wurf +8 Punkte.",
      "type": "manyTailsBonus",
      "value": 8
    },
    {
      "id": "charm_mirror",
      "name": "Blinder Spiegel",
      "cost": 13,
      "text": "Bei 6+ Köpfen im Wurf +8 Punkte.",
      "type": "manyHeadsBonus",
      "value": 8
    },
    {
      "id": "charm_ticket",
      "name": "Zerknittertes Ticket",
      "cost": 5,
      "text": "Shop-Angebote kosten 1 weniger.",
      "type": "shopDiscount",
      "value": 1
    },
    {
      "id": "charm_vault",
      "name": "Mini-Tresor",
      "cost": 16,
      "text": "Start jeder Runde: +5 Punkte.",
      "type": "roundStart",
      "value": 5
    },
    {
      "id": "charm_pendulum",
      "name": "Pendel",
      "cost": 14,
      "text": "Abwechselnd +10% und -5% Zahl-Chance pro Wurf.",
      "type": "pendulum",
      "value": 10
    },
    {
      "id": "charm_lens",
      "name": "Pixellinse",
      "cost": 12,
      "text": "Seltene Münzen erscheinen öfter im Shop.",
      "type": "rareShop",
      "value": 1
    },
    {
      "id": "charm_battery",
      "name": "Leere Batterie",
      "cost": 9,
      "text": "Nach jedem Kauf +2 permanente Punkte auf neue Rundenstarts.",
      "type": "buyCharge",
      "value": 2
    },
    {
      "id": "charm_bell",
      "name": "Silberglöckchen",
      "cost": 15,
      "text": "Bei exakt 4 Zahlen im Wurf: x1.5 Wurfpunkte.",
      "type": "exactFourTailsMult",
      "value": 1.5
    },
    {
      "id": "charm_stamp",
      "name": "Pfandsiegel",
      "cost": 7,
      "text": "Verkaufte Münzen geben +3 Punkte.",
      "type": "sellBonus",
      "value": 3
    },
    {
      "id": "charm_crack",
      "name": "Riss im Boden",
      "cost": 18,
      "text": "Bossziele steigen langsamer.",
      "type": "slowScaling",
      "value": 0.85
    },
    {
      "id": "charm_oil",
      "name": "Automatenöl",
      "cost": 11,
      "text": "Nachwürfe sind 15% wahrscheinlicher.",
      "type": "rerollBoost",
      "value": 15
    },
    {
      "id": "charm_chain",
      "name": "Nickelkette",
      "cost": 17,
      "text": "Jede Zahl nach einer Zahl gibt +1 extra.",
      "type": "tailStreak",
      "value": 1
    },
    {
      "id": "charm_radio",
      "name": "Rauschradio",
      "cost": 14,
      "text": "Zufällige Münze pro Runde erhält +20% Zahl-Chance.",
      "type": "radioBias",
      "value": 20
    },
    {
      "id": "charm_crown",
      "name": "Billige Krone",
      "cost": 22,
      "text": "Teuerste Münze zählt doppelt.",
      "type": "doubleHighest",
      "value": 2
    },
    {
      "id": "charm_thread",
      "name": "Roter Faden",
      "cost": 13,
      "text": "Erster Wurf jeder Runde kann nie unter 4 Punkte fallen.",
      "type": "minFirstThrow",
      "value": 4
    },
    {
      "id": "charm_salt",
      "name": "Salzkreis",
      "cost": 8,
      "text": "Schützt einmal pro Run vor einem verlorenen Ziel.",
      "type": "shield",
      "value": 1
    },
    {
      "id": "charm_halo",
      "name": "Neon-Heiligenschein",
      "cost": 20,
      "text": "Alle Kopf-Effekte sind +1 stärker.",
      "type": "headsBuff",
      "value": 1
    },
    {
      "id": "charm_mask",
      "name": "Pixelfratze",
      "cost": 19,
      "text": "Glitch- und Void-Münzen kosten 30% weniger.",
      "type": "darkDiscount",
      "value": 30
    },
    {
      "id": "charm_key",
      "name": "Rostiger Schlüssel",
      "cost": 25,
      "text": "Shop zeigt 1 zusätzliches Angebot.",
      "type": "extraShop",
      "value": 1
    }
  ]
};
